services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - redis
    redis:
        image: redis

    web2:
      image: nginx
      volumes:
        - ./templates:/etc/nginx/templates
      ports:
        - "8080:80"
      environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80